; PlatformIO Project Configuration File

; Global Environment settings shared across all builds
[env]
build_flags = 
    -I src/core
    -I src/teensy
    -I src/pc

; Teensy Environment (Microcontroller build)
[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
lib_deps = kurte/ILI9341_t3n@0.0.0-alpha+sha.f1bfb81825
; Ignore the PC-specific folder for the Teensy build
build_src_filter = +<*> -<pc/>

; Native Environment (Desktop Linux build)
[env:native]
platform = native
; Ignore Teensy-specific code for the PC build
build_src_filter = +<*> -<teensy/>
build_flags = 
    ${env.build_flags}
    -I /usr/include/SDL2
    -D_REENTRANT
build_src_flags = 
    -lSDL2